### ISSUE TITLE
Feature Request: Support File Hosters (i.e modsfire, gofile, etc..)

### ISSUE THREAD

**Issue by oomfiee** [giantpinkrobots/varia#112]
Currently varia doesnt support file hosters or links that dont point to the direct file.

Example: a download site that will ask u to generate a link or solve a captcha for the download file.

~~I dont know if this is a limitation of varia or aria2~~

**Comment by superuser-miguel** [comment]
I don't believe that is the intended use case. Also, those types would require human interaction. The captcha is built in to avoid these types of mass downloads. 

If I'm not mistaken.

**Comment by giantpinkrobots** [comment]
Varia can download those files that require some kind of interaction to access. I never used Modsfire before but since that was one of your examples I went onto Reddit and tried to download a random file that was hosted there, and the browser extension was able to successfully route the download to Varia. For the websites that require some kind of authentication there is the Basic Auth and Cookies.txt import support.

Adding support to automate the human interactions in order to access the direct download links would be a rather daunting task as all websites do it differently and we'd also need to keep up with the changes they may make to those systems that would break the automation. There's also the fact that a lot of these file sharing websites make money through ads, which wouldn't be shown to the users if the download process was automated away by Varia, so that could also cause problems. I do remember way back in the day JDownloader could download files from the likes of RapidShare like that, so I don't think it would be impossible to do it in some way, but still that is way outside this project's scope. As such I am closing this with a won't fix. (Also sorry that I didn't respond for months)
