### ISSUE TITLE
Check button in speed limit

### ISSUE THREAD

**Issue by Sjoerd1993** [giantpinkrobots/varia#37]
Hey,

I was wondering if there's any purpose to the check button in the speed limit, right next to the units:
![image](https://github.com/giantpinkrobots/varia/assets/68477016/000ace7f-c438-47e0-896b-980b825e759d)

It doesn't seem to be toggle-able, it's always on for me. If it's not really doing anything, I'd consider removing it. Otherwise, I'd consider a change in UI to make it clear what it actually does. 

If it's a confirm button, perhaps it would make more sense if the setting would apply automatically when changing the value in the entry row. If that's not an option because of technical reasons, I'd just use a "Confirm" string instead of a checkmark. Also, it should probably give a toast (Adw.Toast) after clicking to show the user that something actually happened in that case :)

**Comment by giantpinkrobots** [comment]
Hello. Yes, it is a confirm button that saves the configuration. I wanted to avoid adding new text as much as possible because then the translations are incomplete at release. But I suppose the way I went was a bit too vague. Basically first you have to do the configuration and press the check button to save the config, then the toggle will work.

![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/aef11255-5650-4cf4-b97a-ba1190b421ad)
This is the new screen I came up with. It just says "Set Config" now.

![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/491198dc-3cca-4984-b5cd-4a2a800b13fd)
If the user tries to toggle the switch on without doing the configuration first, they will now get a toast message and the switch will toggle off on its own.

I hope this way it will be more coherent.

**Comment by giantpinkrobots** [comment]
Hello, the check button is an "apply" button. You need to press it before toggling the switches. I understand now this might not be very intuitive. So, through suggestions in another issue, I have tweaked the preferences window now.

![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/2d621d8e-5c4b-4faf-8fc7-25430fa5247d)

The switch is now inactive by default, and it waits for the user to fill in the fields first. You can see in the screenshot that the speed limit section is toggleable whereas the authentication section has its switch greyed out because the fields are not filled in.

I think this is much more intuitive and easier to understand now. Thank you for the suggestion. I will push these changes with the next commit. For now I am closing this as completed, please reopen if you have another idea.
