### ISSUE TITLE
(feature) Windows Support (WinUI 3)

### ISSUE THREAD

**Issue by x-0D** [giantpinkrobots/varia#4]
I'd like to see this as alternative to laggy motrix download manager on windows machines too.

**Comment by giantpinkrobots** [comment]
I have never tried to port a GTK app to Windows, but I am going to look into it.

**Comment by x-0D** [comment]
What about moving to wxWidgets? there's python bindings available. Good way to build crossplatform apps. You can use wxGlade interactive ui editor to boost development. wxasync python package are also helpful. (Yes, currently wxWidgets not support UWP apps with WinUI3 elements, but have wxUWP as one of alpha unofficial forks, but it is step forward through truely crossplatform application)

**Comment by giantpinkrobots** [comment]
I have been trying to get Varia working on Windows, and I have succeeded.

![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/a7020ab9-325f-40e8-8bd4-8f3d08aed2ef)

However, when it comes to getting it ready for binary distribution, that's a whole different story. Tried a wide variety of different possible ways of getting it packaged, but it just fought me every step of the way. I can write how I got it to run if someone wants to take up the challenge, but I can say the process is very frustrating.

**Comment by x-0D** [comment]
That's good news! Can you write some guide how to run on windows?

**Comment by giantpinkrobots** [comment]
Basically through the GTK Project's Windows installation guide.

https://www.gtk.org/docs/installations/windows/

Installed MSYS2 on Windows, followed through with the bits related to GTK4 in the guide, and ran the Python file directly without building it with Meson. This way the translations didn't work but at least I got the program to work.

**Comment by giantpinkrobots** [comment]
Okay, I've succeeded in building a standalone Windows version of Varia, but it's kinda buggy. I had to edit the main Python code a bit, and it only supports English right now.

I can't include it directly via GitHub since it's pretty big (it needs to include gtk4 and all dependencies) so I uploaded it on ProtonDrive: [https://drive.proton.me/urls/177E0ESPF4#nPEHZ0Tm6ZnP](https://drive.proton.me/urls/177E0ESPF4#nPEHZ0Tm6ZnP) I included an aria2c.exe as well.

To build it, you need to follow through with GTK's Windows guide and download MSYS2, and within MSYS2 you need python, gtk4, libadwaita and pygobject. You also need to install aria2p with pip, and pyinstaller if you want to build a standalone version.

Running variamain.py directly with the MSYS2 console will launch Varia (you also need to have an aria2c.exe next to it).

To build a standalone version, in the home directory of your MSYS2 you need to have:
- variamain.py
- varia.spec
- icon.ico

next to one another. Running "pyinstaller varia.spec" will build a standalone version. But you also need to provide an aria2c.exe file inside of the dist folder that PyInstaller creates. Clicking variamain.exe will launch the app outside MSYS2.

I will refine these instructions once the app is tested more on Windows and include it on the main README file once I am comfortable enough with it.

**Comment by giantpinkrobots** [comment]
Experimental Windows version added with v2024.2.6.
